[[entry]]
timestamp = 1767225600
appid = "2346300"
title = """看事 Demo"""
[[entry]]
timestamp = 1767225600
appid = "2630940"
title = """World War 2 Agenda Demo"""
[[entry]]
timestamp = 1767225600
appid = "4025300"
title = """Mind Inc Demo"""
[[entry]]
timestamp = 1767225600
appid = "4066170"
title = """Aberrate Inc. Demo"""
[[entry]]
timestamp = 1767225600
appid = "4077190"
title = """千禧失乐园 Demo"""
[[entry]]
timestamp = 1767225600
appid = "4100010"
title = """Aclaíocht do Deamhain Demo"""
[[entry]]
timestamp = 1767225600
appid = "4195550"
title = """The Grant Grover Anthology Demo"""
[[entry]]
timestamp = 1767225600
appid = "4225600"
title = """Kuentame Demo"""
[[entry]]
timestamp = 1767225600
appid = "4229660"
title = """星际圣灵 Demo"""
[[entry]]
timestamp = 1767225600
appid = "4238790"
title = """车辙制造者 Demo"""
[[entry]]
timestamp = 1767225600
appid = "4243630"
title = """KABOOM Farm Demo"""
[[entry]]
timestamp = 1767225600
appid = "4248030"
title = """Tinker Game Demo"""
[[entry]]
timestamp = 1767225600
appid = "4249710"
title = """Find Cats 6 像素猫 Demo"""
[[entry]]
timestamp = 1767225600
appid = "4254420"
title = """Super Magic Book Demo"""
[[entry]]
timestamp = 1767225600
appid = "4258850"
title = """The Adventure of Natsuki Hinomiya DEMO"""
[[entry]]
timestamp = 1767225600
appid = "4260430"
title = """Zodiax Demo"""
[[entry]]
timestamp = 1767225600
appid = "4261100"
title = """Elysie Demo"""
[[entry]]
timestamp = 1767225600
appid = "4273230"
title = """Everfall 2: Idle Dungeon RPG Demo"""
[[entry]]
timestamp = 1767225600
appid = "4275200"
title = """Floral Fury Online Demo"""
[[entry]]
timestamp = 1767312000
appid = "3863820"
title = """Illusive Domain Demo"""
[[entry]]
timestamp = 1767312000
appid = "3954790"
title = """Void Harvest Demo"""
[[entry]]
timestamp = 1767312000
appid = "4049120"
title = """外星反骨仔 Demo"""
[[entry]]
timestamp = 1767312000
appid = "4117370"
title = """Lofi Mahjong Demo"""
[[entry]]
timestamp = 1767312000
appid = "4120840"
title = """Pineapple Legend Demo"""
[[entry]]
timestamp = 1767312000
appid = "4185000"
title = """Dash Dot Die Demo"""
[[entry]]
timestamp = 1767312000
appid = "4214330"
title = """Tick Hop 2 Demo"""
[[entry]]
timestamp = 1767312000
appid = "4222940"
title = """Myth Requiem Demo"""
[[entry]]
timestamp = 1767312000
appid = "4224630"
title = """异星战争 试玩版"""
[[entry]]
timestamp = 1767312000
appid = "4226450"
title = """Nightpyre Demo"""
[[entry]]
timestamp = 1767312000
appid = "4239260"
title = """Z12 Demo"""
[[entry]]
timestamp = 1767312000
appid = "4244070"
title = """Garden Ink Demo"""
[[entry]]
timestamp = 1767312000
appid = "4253360"
title = """Magic Tower: Legion Demo"""
[[entry]]
timestamp = 1767312000
appid = "4255750"
title = """In Search of Freedom Demo"""
[[entry]]
timestamp = 1767312000
appid = "4256770"
title = """Spring Me Up Demo"""
[[entry]]
timestamp = 1767312000
appid = "4257060"
title = """Molekraft Demo"""
[[entry]]
timestamp = 1767312000
appid = "4260710"
title = """AINUR Demo"""
[[entry]]
timestamp = 1767312000
appid = "4264940"
title = """Open Fire: Ready Demo"""
[[entry]]
timestamp = 1767312000
appid = "4272770"
title = """Junkyard File Demo"""
[[entry]]
timestamp = 1767312000
appid = "4273410"
title = """Explosiovania Demo"""
[[entry]]
timestamp = 1767312000
appid = "4276290"
title = """Ethan's Watch Demo"""
[[entry]]
timestamp = 1767312000
appid = "4276760"
title = """Talisman Demo"""
[[entry]]
timestamp = 1767398400
appid = "4138310"
title = """Adventure TD Demo"""
[[entry]]
timestamp = 1767398400
appid = "4151940"
title = """Remnants of Sin Demo"""
[[entry]]
timestamp = 1767398400
appid = "4237350"
title = """Cleared For Impact Demo"""
[[entry]]
timestamp = 1767398400
appid = "4257920"
title = """Marble Quest Demo"""
[[entry]]
timestamp = 1767398400
appid = "4260660"
title = """Trushybin & Removin: What I Couldn’t Delete Demo"""
[[entry]]
timestamp = 1767398400
appid = "4269680"
title = """King's Downfall Demo"""
[[entry]]
timestamp = 1767398400
appid = "4277670"
title = """Royal Dental Demo"""
[[entry]]
timestamp = 1767484800
appid = "3662000"
title = """RogueDiceR Demo"""
[[entry]]
timestamp = 1767484800
appid = "3987010"
title = """Mayor Life Simulator Demo"""
[[entry]]
timestamp = 1767484800
appid = "4034510"
title = """愿你拿一手同花顺 May the cards lay out a straight Demo"""
[[entry]]
timestamp = 1767484800
appid = "4084950"
title = """CapyBash Demo"""
[[entry]]
timestamp = 1767484800
appid = "4223890"
title = """Book Of The Abyss Demo"""
[[entry]]
timestamp = 1767484800
appid = "4250970"
title = """GLIDE Demo"""
[[entry]]
timestamp = 1767571200
appid = "3623560"
title = """Orbital Descent Demo"""
[[entry]]
timestamp = 1767571200
appid = "4069970"
title = """Daughter of the Rift Demo"""
[[entry]]
timestamp = 1767571200
appid = "4226030"
title = """コメンテーター Demo"""
[[entry]]
timestamp = 1767571200
appid = "4250640"
title = """Red Sky Demo"""
[[entry]]
timestamp = 1767571200
appid = "4265290"
title = """Lost in Hieroglyphs: A Hidden Objects Expedition Demo"""
[[entry]]
timestamp = 1767571200
appid = "4272450"
title = """Trapped on the FlipSide - Demo"""
[[entry]]
timestamp = 1767571200
appid = "4275960"
title = """Wisdom Tower Demo"""
[[entry]]
timestamp = 1767571200
appid = "4280430"
title = """Bowlers Demo"""
[[entry]]
timestamp = 1767657600
appid = "3907600"
title = """My Desktop Puppy: 我的桌面小狗 Demo"""
[[entry]]
timestamp = 1767657600
appid = "4006960"
title = """Druid of Hungwood Demo"""
[[entry]]
timestamp = 1767657600
appid = "4088160"
title = """Fire & Crown: A Demo of the Hundred Years' War"""
[[entry]]
timestamp = 1767657600
appid = "4193910"
title = """Chhota Bheem Kitchen Adventures Demo"""
[[entry]]
timestamp = 1767657600
appid = "4210320"
title = """Reincarnated as a Dark Lord Before Taking Over the World with Power 999999999 Demo"""
[[entry]]
timestamp = 1767657600
appid = "4218920"
title = """Forks & Daggers Demo"""
[[entry]]
timestamp = 1767657600
appid = "4232980"
title = """NovelStudio Demo"""
[[entry]]
timestamp = 1767657600
appid = "4235510"
title = """Balladrion Demo"""
[[entry]]
timestamp = 1767657600
appid = "4241950"
title = """TimeOut Demo"""
[[entry]]
timestamp = 1767657600
appid = "4256660"
title = """Restoration Demo"""
[[entry]]
timestamp = 1767657600
appid = "4260920"
title = """Memory Maze Demo"""
[[entry]]
timestamp = 1767657600
appid = "4263270"
title = """RAM Downloader Demo"""
[[entry]]
timestamp = 1767657600
appid = "4266230"
title = """交错方阵 Crossed Tiles Demo"""
[[entry]]
timestamp = 1767657600
appid = "4272550"
title = """迷你种田 Demo"""
[[entry]]
timestamp = 1767657600
appid = "4276400"
title = """Blood for the Queen Demo"""
[[entry]]
timestamp = 1767657600
appid = "4281610"
title = """死とは何か？ Demo"""
[[entry]]
timestamp = 1767657600
appid = "4281970"
title = """Kimi ga Nozomu Eien Enhanced Edition Demo"""
[[entry]]
timestamp = 1767657600
appid = "4286560"
title = """The Long Winter Demo"""
[[entry]]
timestamp = 1767657600
appid = "544450"
title = """Typing with Jester Demo"""
[[entry]]
timestamp = 1767744000
appid = "1360770"
title = """甜蜜岛 Demo"""
[[entry]]
timestamp = 1767744000
appid = "2499870"
title = """DRAGON QUEST VII Reimagined Demo"""
[[entry]]
timestamp = 1767744000
appid = "3876410"
title = """Drunk Dork On Pitchfork Demo"""
[[entry]]
timestamp = 1767744000
appid = "3876520"
title = """Low Battery Demo"""
[[entry]]
timestamp = 1767744000
appid = "4128430"
title = """The Forsaken Tomb Demo"""
[[entry]]
timestamp = 1767744000
appid = "4145930"
title = """EmyLiveShow Origins: Emy The Vampire Queen Demo"""
[[entry]]
timestamp = 1767744000
appid = "4157210"
title = """Dungeon Apollonios Demo"""
[[entry]]
timestamp = 1767744000
appid = "4170150"
title = """Medic Mayhem Demo"""
[[entry]]
timestamp = 1767744000
appid = "4186990"
title = """女儿国的诅咒 Demo"""
[[entry]]
timestamp = 1767744000
appid = "4200230"
title = """Summoner's Cookbook Demo"""
[[entry]]
timestamp = 1767744000
appid = "4213790"
title = """The Gas Station : Graveyard Shift Demo"""
[[entry]]
timestamp = 1767744000
appid = "4213870"
title = """Andromis Demo"""
[[entry]]
timestamp = 1767744000
appid = "4218560"
title = """LOVE IN BATTLE MACHINE: Furry arena DEMO"""
[[entry]]
timestamp = 1767744000
appid = "4233280"
title = """Mana Battle Demo"""
[[entry]]
timestamp = 1767744000
appid = "4239110"
title = """Pages of Tomorrow Demo"""
[[entry]]
timestamp = 1767744000
appid = "4248500"
title = """TwinZ Demo"""
[[entry]]
timestamp = 1767744000
appid = "4266630"
title = """ZenWash Demo"""
[[entry]]
timestamp = 1767744000
appid = "4267790"
title = """Seeing Double Demo"""
[[entry]]
timestamp = 1767744000
appid = "4275740"
title = """Creaworm Demo"""
[[entry]]
timestamp = 1767744000
appid = "4283140"
title = """Foul Demo"""
[[entry]]
timestamp = 1767744000
appid = "4287950"
title = """Risky Mining Demo"""
[[entry]]
timestamp = 1767744000
appid = "4288100"
title = """Shadow Corruption Unit Demo"""
[[entry]]
timestamp = 1767744000
appid = "4290240"
title = """Eternal Halls Demo"""
[[entry]]
timestamp = 1767744000
appid = "4291660"
title = """Scrub Dudes Demo"""
[[entry]]
timestamp = 1767744000
appid = "4291860"
title = """Dig For Riches Demo"""
[[entry]]
timestamp = 1767744000
appid = "4292990"
title = """Glyph Gambit Demo"""
[[entry]]
timestamp = 1767830400
appid = "3801310"
title = """Stack to Ascension Demo"""
[[entry]]
timestamp = 1767830400
appid = "4010610"
title = """Chosen Garden demo"""
[[entry]]
timestamp = 1767830400
appid = "4054630"
title = """Astrobuilder Demo"""
[[entry]]
timestamp = 1767830400
appid = "4189040"
title = """Galactic Arms Demo"""
[[entry]]
timestamp = 1767830400
appid = "4252670"
title = """BasketBlow Demo"""
[[entry]]
timestamp = 1767830400
appid = "4259270"
title = """Convenience Store Simulator Demo"""
[[entry]]
timestamp = 1767830400
appid = "4260440"
title = """Down Hell Demo"""
[[entry]]
timestamp = 1767830400
appid = "4278270"
title = """駅前のカフカ Demo"""
[[entry]]
timestamp = 1768003200
appid = "4125540"
title = """Aurora Heights Demo"""
[[entry]]
timestamp = 1768003200
appid = "4251300"
title = """Burger Shift: Team Rush Demo"""
[[entry]]
timestamp = 1768003200
appid = "4308230"
title = """Signal Zone Demo"""
[[entry]]
timestamp = 1768089600
appid = "3825670"
title = """咎絆ぎ Chapter1 Demo"""
[[entry]]
timestamp = 1768089600
appid = "3967200"
title = """Eyehold Blocks Demo"""
[[entry]]
timestamp = 1768089600
appid = "4187560"
title = """The Industrial Council Demo"""
[[entry]]
timestamp = 1768089600
appid = "4217500"
title = """Mainframe Men Demo"""
[[entry]]
timestamp = 1768089600
appid = "4222200"
title = """Duppy Detective Tashia Demo"""
[[entry]]
timestamp = 1768089600
appid = "4238000"
title = """Artifact Hunt: Yao Demo"""
[[entry]]
timestamp = 1768089600
appid = "4239730"
title = """Spellsy Demo"""
[[entry]]
timestamp = 1768089600
appid = "4245000"
title = """Memory Draw Demo"""
[[entry]]
timestamp = 1768089600
appid = "4250450"
title = """Paid in Blood (Pre-Release Demo)"""
[[entry]]
timestamp = 1768089600
appid = "4258940"
title = """KunKunNest Demo"""
[[entry]]
timestamp = 1768089600
appid = "4273860"
title = """Cryptoria Demo"""
[[entry]]
timestamp = 1768089600
appid = "4274150"
title = """Foghorns Drown Demo"""
[[entry]]
timestamp = 1768089600
appid = "4275070"
title = """Drive Together Demo"""
[[entry]]
timestamp = 1768089600
appid = "4282570"
title = """The Last Wizard - A Goblin Detective Mystery Demo"""
[[entry]]
timestamp = 1768089600
appid = "4291260"
title = """Dance Dance Detective Demo"""
[[entry]]
timestamp = 1768089600
appid = "4300240"
title = """quadrant Demo"""
[[entry]]
timestamp = 1768089600
appid = "4303050"
title = """Movie Business Demo"""
[[entry]]
timestamp = 1768089600
appid = "4304680"
title = """Lifecycles of the Traveler Spider Demo"""
[[entry]]
timestamp = 1768176000
appid = "2928230"
title = """There is NO PLAN B Demo"""
[[entry]]
timestamp = 1768176000
appid = "2947990"
title = """Ancestral Players Demo"""
[[entry]]
timestamp = 1768176000
appid = "4188940"
title = """Panzer Fantasy 16 Bits Demo"""
[[entry]]
timestamp = 1768176000
appid = "4222120"
title = """We need a doorman. Demo"""
[[entry]]
timestamp = 1768176000
appid = "4230860"
title = """Code: 9 Demo"""
[[entry]]
timestamp = 1768176000
appid = "4270880"
title = """Obsidian Moon Demo"""
[[entry]]
timestamp = 1768176000
appid = "4283220"
title = """NIPH Demo"""
[[entry]]
timestamp = 1768435200
appid = "3781070"
title = """From The Void Demo"""
[[entry]]
timestamp = 1768435200
appid = "3820790"
title = """Kinny and the Cosmic Cauldron Demo"""
[[entry]]
timestamp = 1768435200
appid = "4119060"
title = """REGRET - Demo"""
[[entry]]
timestamp = 1768435200
appid = "4220240"
title = """Warfleet Captains Demo"""
[[entry]]
timestamp = 1768435200
appid = "4220250"
title = """Mushroom Forest Demo"""
[[entry]]
timestamp = 1768435200
appid = "4278700"
title = """Mimetic Demo"""
[[entry]]
timestamp = 1768435200
appid = "4291580"
title = """Lost Wiki: Kozlovka Demo"""
[[entry]]
timestamp = 1768435200
appid = "4298590"
title = """Nano Dash Demo"""
[[entry]]
timestamp = 1768435200
appid = "4321470"
title = """Turscar Isle Demo"""
[[entry]]
timestamp = 1768435200
appid = "4322950"
title = """WHODUNNIT Episode 1: Hitting Singles"""
[[entry]]
timestamp = 1768521600
appid = "2649160"
title = """ALYSSA - Demo"""
[[entry]]
timestamp = 1768521600
appid = "3588850"
title = """Tree's Love Crossing Above: Origin"""
[[entry]]
timestamp = 1768521600
appid = "3973540"
title = """A Ragdoll Rage Game Demo"""
[[entry]]
timestamp = 1768521600
appid = "3992510"
title = """RIG Riot Demo"""
[[entry]]
timestamp = 1768521600
appid = "4113610"
title = """The Hilarious Three Kingdoms 2 Demo"""
[[entry]]
timestamp = 1768521600
appid = "4122670"
title = """ネクロジェネシス 体験版"""
[[entry]]
timestamp = 1768521600
appid = "4141810"
title = """Astro Loopers Demo"""
[[entry]]
timestamp = 1768521600
appid = "4146750"
title = """Athelan Battlegrounds Demo"""
[[entry]]
timestamp = 1768521600
appid = "4207490"
title = """Sole Salvation Demo"""
[[entry]]
timestamp = 1768521600
appid = "4250400"
title = """2048 方块争霸排行榜 Demo"""
[[entry]]
timestamp = 1768521600
appid = "4254850"
title = """Cozy Home Demo"""
[[entry]]
timestamp = 1768521600
appid = "4258310"
title = """I Wanna Touch Demo"""
[[entry]]
timestamp = 1768521600
appid = "4258320"
title = """Rabbit Detective Demo"""
[[entry]]
timestamp = 1768521600
appid = "4259310"
title = """Chant Wizard Demo"""
[[entry]]
timestamp = 1768521600
appid = "4265910"
title = """Ajnabee - The Unknown Demo"""
[[entry]]
timestamp = 1768521600
appid = "4270260"
title = """Kodoku：As the Moon Mourns Demo"""
[[entry]]
timestamp = 1768521600
appid = "4275170"
title = """山海异仙 Demo"""
[[entry]]
timestamp = 1768521600
appid = "4275380"
title = """Neon Dash Demo"""
[[entry]]
timestamp = 1768521600
appid = "4296690"
title = """Wish Of Hers Demo"""
[[entry]]
timestamp = 1768521600
appid = "4303790"
title = """Acrolyte Demo"""
[[entry]]
timestamp = 1768521600
appid = "4307030"
title = """Unwilling Host Demo"""
[[entry]]
timestamp = 1768521600
appid = "4310820"
title = """Fracture Field Demo"""
[[entry]]
timestamp = 1768521600
appid = "4313750"
title = """Your Maid - Demo"""
[[entry]]
timestamp = 1768694400
appid = "3531870"
title = """さくらいろテトラプリズム 体験版"""
[[entry]]
timestamp = 1768694400
appid = "4205610"
title = """Tales of Fear - Episode Zero Demo"""
[[entry]]
timestamp = 1768694400
appid = "4216900"
title = """Pollinate or Die Demo"""
[[entry]]
timestamp = 1768694400
appid = "4231180"
title = """Spells & Shells Demo"""
[[entry]]
timestamp = 1768694400
appid = "4255700"
title = """Menacetide Demo"""
[[entry]]
timestamp = 1768694400
appid = "4256790"
title = """NTR Phone Demo"""
[[entry]]
timestamp = 1768694400
appid = "4270480"
title = """我喜欢的白毛美少女不可能是凶手 Demo"""
[[entry]]
timestamp = 1768694400
appid = "4277490"
title = """Naughty Doug Demo"""
[[entry]]
timestamp = 1768694400
appid = "4279870"
title = """四合 Quadrangle Demo"""
[[entry]]
timestamp = 1768694400
appid = "4292010"
title = """Cthulhu 1920 Demo"""
[[entry]]
timestamp = 1768694400
appid = "4304250"
title = """Fun Zone Omega Demo"""
[[entry]]
timestamp = 1768694400
appid = "4308930"
title = """小球冲刺 Demo"""
[[entry]]
timestamp = 1768694400
appid = "4315890"
title = """Chronosmith's Saga Demo"""
[[entry]]
timestamp = 1768694400
appid = "4318700"
title = """Dungeon Mutt Demo"""
[[entry]]
timestamp = 1768694400
appid = "4323850"
title = """Hovercrafts x Nihilism Demo"""
[[entry]]
timestamp = 1768780800
appid = "3795860"
title = """Propaganda VS Zombies 2 Demo"""
[[entry]]
timestamp = 1768780800
appid = "3970140"
title = """Noir Lords Demo"""
[[entry]]
timestamp = 1768780800
appid = "4281300"
title = """Alpha Force Zero Demo"""
[[entry]]
timestamp = 1768780800
appid = "4282400"
title = """机械操作实训营 Demo"""
[[entry]]
timestamp = 1768780800
appid = "4290740"
title = """Blind Bluff Demo"""
[[entry]]
timestamp = 1768780800
appid = "4299410"
title = """LucidVR Video Player Demo"""
[[entry]]
timestamp = 1768780800
appid = "4307640"
title = """Tooned Out Duo Dippin Demo"""
[[entry]]
timestamp = 1768780800
appid = "4320240"
title = """RE-TAPED Demo"""
[[entry]]
timestamp = 1768780800
appid = "4321100"
title = """Midnight Ramen Shop Demo"""
[[entry]]
timestamp = 1768780800
appid = "4329910"
title = """The Dungeon Of Horror Demo"""
